version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU

xamarin:
  email: matthew.leibowitz@xamarin.com
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true

build_script:
- ps: .\build.ps1
  
artifacts:
 - path: output
 - path: output\*.nupkg
 - path: output\*.xam
